name: SCR
main: me.devtec.scr.Loader
author: DevTec, StraikerinaCZ
version: 1.0-Alpha
api-version: 1.13
description: Fully customizable plugin with many features!
depend: [TheAPI]
loadbefore: [Vault,Paintball,WorldGuard,Residence,MobArena,SpecializedCrates,ExcellentCrates,GoldenCrates,RevoltCrates,AdvancedMonthlyCrates,CrazyCrates,CrateReloaded]
softdepend: [PlaceholderAPI,Vault,HeadDatabase,LuckPerms,dynmap]
spigot-id: 71147
website: https://www.spigotmc.org/resources/71147/