name: SCR
main: me.devtec.scr.Loader
author: DevTec
version: 0.1-Alpha
api-version: 1.13
description: Fully customizable plugin with many features!
depend: [TheAPI]
loadbefore: [Paintball,WorldGuard,Residence,MobArena,SpecializedCrates,GoldenCrates,RevoltCrates,AdvancedMonthlyCrates,CrazyCrates,CrateReloaded]
softdepend: [HeadDatabase,Essentials,WorldEdit,LuckPerms,dynmap]
spigot-id: 71147
website: https://www.spigotmc.org/resources/71147/