name: SCR
main: me.devtec.scr.Loader
author: DevTec, StraikerinaCZ, Houska02
version: 9.0
api-version: 1.13
description: Fully customizable plugin with many features!
depend: [TheAPI]
loadbefore: [Paintball,WorldGuard,Residence,MobArena,SpecializedCrates,GoldenCrates,RevoltCrates,AdvancedMonthlyCrates,CrazyCrates,CrateReloaded]
softdepend: [HeadDatabase,Essentials,WorldEdit,LuckPerms,dynmap]
website: https://www.spigotmc.org/resources/71147/