# Built-in translations: en (English), ru (Russia), cz (Czechia)
translation: en

# Do you want to log to the file processing of things below?
loggers:
  # Beware! Jobs plugin or similiar jobs plugins can spam this log.
  economy: false
  # Log only if rule result is true
  rules: false
  # Logger of joins & quits of players
  join-quit: false
  # Logger of processing SCR commands
  process-cmds: false

positive:
- "yes"
- "true"
- "on"
- "allow"

negative:
- "no"
- "false"
- "off"
- "disallow"

modules:
  actionbar: false
  bossbar: false
  scoreboard: true
  tablist: true
  scr-economy: true
  chat: true
  # If you want to disable whole loader of custom commands, set value to false
  custom-cmds: true
  # If you want to disable whole loader of custom guis (with commands), set value to false
  custom-guis: true
  # For other modules, open the listeners.yml file in the listeners folder.
  # You can disable or modify the commands in commands.yml and custom-cmds folder

actions:
  vanish:
    onJoin:
      commands: []
      broadcast: []
      messages:
      - "Vanish is still enabled"
    onQuit:
      commands: []
      messages: []
      broadcast: []
    start:
      commands: []
      messages: []
      broadcast:
      - "%player_displayname% &7left the game"
    stop:
      commands: []
      messages: []
      broadcast:
      - "%player_displayname% &7joined to the game"
  afk:
    start:
      commands: []
      messages: []
      broadcast:
      - "%player_displayname% &7is AFK"
    process:
      30min:
        messages: []
        commands:
        - "kick %player_name% Afking isn't allowed!"
        broadcast:
        - "%player_displayname% &7kicked for afking"
      # 15min:
      #   repeatable: true
      #   commands:
      #   - "eco take %player_name% 100 -s"
      #   messages:
      #   - "&c-100$ &7has been withdrawn from your account for afking"
    stop:
      commands: []
      messages: []
      broadcast:
      - "%player_displayname% &7is no longer AFK"

control-panel:
  restart:
    default-time: 5s
    start:
      commands: []
      broadcast:
      - "Restart of server in %time%"
    process:
      30:
        commands: []
        broadcast:
        - "Restart of server in 30s"
      15:
        commands: []
        broadcast:
        - "Restart of server in 15s"
      5:
        commands: []
        broadcast:
        - "Restart of server in 5s"
      3:
        commands: []
        broadcast:
        - "Restart of server in 3s"
      2:
        commands: []
        broadcast:
        - "Restart of server in 2s"
      1:
        commands: []
        broadcast:
        - "Restart of server in 1s"
    end:
      wait: 3s
      commands:
      - "send * lobby"
      broadcast: []
    cancel:
      commands: []
      broadcast:
      - "Server restart cancelled!"
      
  stop:
    default-time: 5s
    start:
      commands: []
      broadcast:
      - "Shutdown of server in %time%"
    process:
      30:
        commands: []
        broadcast:
        - "Shutdown of server in 30s"
      15:
        commands: []
        broadcast:
        - "Shutdown of server in 15s"
      5:
        commands: []
        broadcast:
        - "Shutdown of server in 5s"
      3:
        commands: []
        broadcast:
        - "Shutdown of server in 3s"
      2:
        commands: []
        broadcast:
        - "Shutdown of server in 2s"
      1:
        commands: []
        broadcast:
        - "Shutdown of server in 1s"
    end:
      wait: 3s
      commands:
      - "send * lobby"
      broadcast: []
    cancel:
      commands: []
      broadcast:
      - "Server shutdown cancelled!"
      
  reload:
    default-time: 5s
    start:
      commands: []
      broadcast:
      - "Reload of server in %time%"
    process:
      30:
        commands: []
        broadcast:
        - "Reload of server in 30s"
      15:
        commands: []
        broadcast:
        - "Reload of server in 15s"
      5:
        commands: []
        broadcast:
        - "Reload of server in 5s"
      3:
        commands: []
        broadcast:
        - "Reload of server in 3s"
      2:
        commands: []
        broadcast:
        - "Reload of server in 2s"
      1:
        commands: []
        broadcast:
        - "Reload of server in 1s"
    end:
      commands: []
      broadcast:
      - "Reloading the server, please wait..."
    cancel:
      commands: []
      broadcast:
      - "Server reload has been cancelled"